/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Tugas;

import javax.swing.JOptionPane;

/**
 *
 * @author asus
 */
public class Tugas1_2 extends javax.swing.JFrame {
    double gbruto;
    /**
     * Creates new form Tugas1_2
     */
    public Tugas1_2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jJamker = new javax.swing.JTextField();
        jBruto = new javax.swing.JButton();
        jBersih = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        eTarif = new javax.swing.JTextField();
        gBruto = new javax.swing.JTextField();
        gBersih = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lbLOGO = new javax.swing.JLabel();
        btSelesai = new javax.swing.JButton();
        btReset = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(jJamker);
        jJamker.setBounds(130, 150, 194, 37);

        jBruto.setBackground(new java.awt.Color(0, 153, 153));
        jBruto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jBruto.setForeground(new java.awt.Color(255, 255, 255));
        jBruto.setText("HITUNG GAJI BRUTO");
        jBruto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBrutoActionPerformed(evt);
            }
        });
        getContentPane().add(jBruto);
        jBruto.setBounds(140, 260, 170, 35);

        jBersih.setBackground(new java.awt.Color(0, 153, 153));
        jBersih.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jBersih.setForeground(new java.awt.Color(255, 255, 255));
        jBersih.setText("HITUNG GAJI BERSIH");
        jBersih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBersihActionPerformed(evt);
            }
        });
        getContentPane().add(jBersih);
        jBersih.setBounds(140, 360, 170, 35);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 51));
        jLabel2.setText("Gaji Bersih :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(100, 410, 70, 30);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 0, 51));
        jLabel3.setText("Tarif Per-Jam");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(110, 210, 80, 30);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 0, 51));
        jLabel4.setText("Gaji Bruto :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(100, 310, 70, 30);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 0, 51));
        jLabel5.setText("Jumlah Jam Kerja 1 Minggu");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(150, 120, 160, 16);

        eTarif.setEditable(false);
        eTarif.setBackground(new java.awt.Color(255, 255, 255));
        eTarif.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        eTarif.setForeground(new java.awt.Color(102, 0, 51));
        eTarif.setText("Rp. 10.000");
        eTarif.setDisabledTextColor(new java.awt.Color(0, 102, 102));
        getContentPane().add(eTarif);
        eTarif.setBounds(200, 210, 120, 30);

        gBruto.setEditable(false);
        gBruto.setBackground(new java.awt.Color(255, 255, 255));
        gBruto.setForeground(new java.awt.Color(102, 0, 51));
        gBruto.setSelectionColor(new java.awt.Color(0, 0, 102));
        getContentPane().add(gBruto);
        gBruto.setBounds(190, 312, 140, 30);

        gBersih.setEditable(false);
        gBersih.setBackground(new java.awt.Color(255, 255, 255));
        gBersih.setForeground(new java.awt.Color(102, 0, 51));
        getContentPane().add(gBersih);
        gBersih.setBounds(190, 412, 140, 30);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 0, 0);

        lbLOGO.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lbLOGO.setForeground(new java.awt.Color(255, 255, 255));
        lbLOGO.setText("CV. Djawa Team");
        lbLOGO.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        getContentPane().add(lbLOGO);
        lbLOGO.setBounds(150, 20, 160, 50);

        btSelesai.setBackground(new java.awt.Color(0, 153, 153));
        btSelesai.setForeground(new java.awt.Color(255, 255, 255));
        btSelesai.setText("SELESAI");
        btSelesai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSelesaiActionPerformed(evt);
            }
        });
        getContentPane().add(btSelesai);
        btSelesai.setBounds(140, 500, 80, 23);

        btReset.setBackground(new java.awt.Color(0, 153, 153));
        btReset.setForeground(new java.awt.Color(255, 255, 255));
        btReset.setText("RESET");
        btReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btResetActionPerformed(evt);
            }
        });
        getContentPane().add(btReset);
        btReset.setBounds(230, 500, 80, 23);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tugas/wayang.png"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(80, 60, 300, 470);

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tugas/conut (1).jpeg"))); // NOI18N
        getContentPane().add(bg);
        bg.setBounds(0, -10, 449, 620);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBrutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBrutoActionPerformed
        int lembur;
        String jamkerja = jJamker.getText();
        int Tarif = 10000 ;

        int intJam = Integer.parseInt(jamkerja);

        if (intJam > 40 ){
            lembur = intJam - 40;
            gbruto = (40 * 10000)+ (lembur * (10000*1.5));
        }else {
            gbruto = intJam * 10000;
        }
        eTarif.setText("Rp. 10000");
        gBruto.setText("Rp. "+ Double.toString(gbruto));
    }//GEN-LAST:event_jBrutoActionPerformed

    private void jBersihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBersihActionPerformed
        double gbersih = gbruto * 0.9;
            gBersih.setText("Rp. " + Double.toString(gbersih));
    }//GEN-LAST:event_jBersihActionPerformed

    private void btSelesaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSelesaiActionPerformed
        String jamkerja = jJamker.getText();
        
        if (jamkerja.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Anda belum mengisi");
        } else {
        
        String jamker = jJamker.getText();
        String bruto = gBruto.getText();
        String bersih = gBersih.getText();
        
        JOptionPane.showMessageDialog(this, "Jumlah Jam Kerja 1 Minggu : " + jamker + "\nGaji Bruto : " + bruto + "\nGaji Bersih : " + bersih );
        }
    }//GEN-LAST:event_btSelesaiActionPerformed

    private void btResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btResetActionPerformed
        jJamker.setText("");
        gBruto.setText("");
        gBersih.setText("");
    }//GEN-LAST:event_btResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tugas1_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tugas1_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tugas1_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tugas1_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tugas1_2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JButton btReset;
    private javax.swing.JButton btSelesai;
    private javax.swing.JTextField eTarif;
    private javax.swing.JTextField gBersih;
    private javax.swing.JTextField gBruto;
    private javax.swing.JButton jBersih;
    private javax.swing.JButton jBruto;
    private javax.swing.JTextField jJamker;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lbLOGO;
    // End of variables declaration//GEN-END:variables
}
